name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Silla.sln

      - name: Build
        run: dotnet build Silla.sln --configuration Release --no-restore

      # Optional: run tests if you add test projects later
      - name: Test
        run: dotnet test Silla.sln --no-build --verbosity normal
